import os
import json
import logging
from typing import List, Dict, Any, Optional
from openai import AsyncOpenAI

_log = logging.getLogger(__name__)

async def create_and_submit_batch(
    chunks_text: List[str], 
    document_content: str, 
    model_name: str = "gpt-4o-mini"
) -> str | None:
    """
    모든 청크 요약 요청을 .jsonl 파일로 만들고 OpenAI Batch API에 전송합니다.
    성공 시 batch_id를 리턴합니다.
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        _log.error("OPENAI_API_KEY가 없습니다. Batch API를 호출할 수 없습니다.")
        return None

    client = AsyncOpenAI(api_key=api_key)
    batch_file_path = "batch_requests.jsonl"
    
    from .utils import contextual_chunk_system_prompt, contextual_chunk_user_prompt

    # 1. JSONL 파일 생성
    with open(batch_file_path, "w", encoding="utf-8") as f:
        for idx, chunk_text in enumerate(chunks_text):
            user_content = contextual_chunk_user_prompt.format(
                document_content=document_content,
                chunk_content=chunk_text
            )
            
            request_obj = {
                "custom_id": f"chunk-{idx}",
                "method": "POST",
                "url": "/v1/chat/completions",
                "body": {
                    "model": model_name,
                    "temperature": 0.0,
                    "messages": [
                        {"role": "system", "content": contextual_chunk_system_prompt},
                        {"role": "user", "content": user_content}
                    ]
                }
            }
            f.write(json.dumps(request_obj, ensure_ascii=False) + "\n")

    _log.info(f"Batch JSONL 파일 생성 완료: {batch_file_path} (총 {len(chunks_text)}건)")

    # 2. 파일 업로드 및 Batch 제출
    try:
        with open(batch_file_path, "rb") as f:
            batch_input_file = await client.files.create(
                file=f,
                purpose="batch"
            )
        
        batch = await client.batches.create(
            input_file_id=batch_input_file.id,
            endpoint="/v1/chat/completions",
            completion_window="24h",
            metadata={
                "description": "Contextual chunk summary batch job"
            }
        )
        
        _log.info(f"✅ OpenAI Batch 전송 완료! Batch ID: {batch.id}")
        return batch.id
        
    except Exception as e:
        _log.error(f"Batch 전송 중 에러 발생: {e}")
        return None


async def check_batch_status(batch_id: str) -> str:
    """
    주어진 Batch ID의 현재 상태를 확인합니다.
    (예: "validating", "in_progress", "completed", "failed", "expired")
    """
    api_key = os.getenv("OPENAI_API_KEY")
    client = AsyncOpenAI(api_key=api_key)
    
    batch = await client.batches.retrieve(batch_id)
    return batch.status


async def retrieve_batch_results(batch_id: str) -> Dict[int, str]:
    """
    Batch 처리가 완료(completed)되었을 때 호출하여 결과 텍스트를 파싱해옵니다.
    반환 형태: {chunk_index: summary_text}
    """
    api_key = os.getenv("OPENAI_API_KEY")
    client = AsyncOpenAI(api_key=api_key)
    
    batch = await client.batches.retrieve(batch_id)
    
    if batch.status != "completed":
        raise ValueError(f"Batch is not completed yet. Current status: {batch.status}")
        
    if not batch.output_file_id:
        raise ValueError("No output file generated by the batch job.")

    # 1. 결과 파일 내용 다운로드
    file_response = await client.files.content(batch.output_file_id)
    content = file_response.read().decode("utf-8")
    
    # 2. JSONL 파싱하여 chunk_idx 별 요약 매핑
    results_map = {}
    for line in content.strip().split('\n'):
        if not line.strip():
            continue
        data = json.loads(line)
        custom_id = data.get("custom_id", "")
        if custom_id.startswith("chunk-"):
            try:
                idx = int(custom_id.split("-")[1])
                choices = data.get("response", {}).get("body", {}).get("choices", [])
                if choices:
                    summary = choices[0].get("message", {}).get("content", "")
                    results_map[idx] = summary.strip()
            except Exception as e:
                _log.error(f"결과 파싱 오류 ({custom_id}): {e}")
                
    return results_map
